Sample Name: QDnew1
<SeaBreezeDevice HR4000:HR4C222>
Current Position:  0.0
0.0
Delay:  1.0
Position: 0.0 degrees at angle
Final Position: 0.0 degrees
Current Position:  0.0
10.0
Delay:  1.4
Position: 10.0 degrees at angle
Final Position: 10.0 degrees
Current Position:  10.0
10.0
Delay:  1.4
Position: 20.0 degrees at angle
Final Position: 20.0 degrees
Current Position:  20.0
10.0
Delay:  1.4
Position: 30.0 degrees at angle
Final Position: 30.0 degrees
Current Position:  30.0
10.0
Delay:  1.4
Position: 40.0 degrees at angle
Final Position: 40.0 degrees
Current Position:  40.0
10.0
Delay:  1.4
Position: 50.0 degrees at angle
Final Position: 50.0 degrees
>>>Moved to 0 Deg
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\naqee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Project\AdvanceOpticalTechnology\appv2.py", line 177, in moveangle
    self.motor_controller.getvelocity()
AttributeError: 'ThorlabsMotionController' object has no attribute 'getvelocity'
Live spectrum started
<SeaBreezeDevice HR4000:HR4C222> for live spectrum
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\naqee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Project\AdvanceOpticalTechnology\appv2.py", line 177, in moveangle
    self.motor_controller.getvelocity()
AttributeError: 'ThorlabsMotionController' object has no attribute 'getvelocity'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\naqee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Project\AdvanceOpticalTechnology\appv2.py", line 460, in stop_live_spectrum
    current_angle = int(self.motor_controller.inst.position())
AttributeError: 'ThorlabsMotionController' object has no attribute 'inst'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\naqee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Project\AdvanceOpticalTechnology\appv2.py", line 460, in stop_live_spectrum
    current_angle = int(self.motor_controller.inst.position())
AttributeError: 'ThorlabsMotionController' object has no attribute 'inst'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\naqee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Project\AdvanceOpticalTechnology\appv2.py", line 460, in stop_live_spectrum
    current_angle = int(self.motor_controller.inst.position())
AttributeError: 'ThorlabsMotionController' object has no attribute 'inst'
